//The contents in this file have been auto-generated by Visual Studio.
//As such, it is not recommended to make any manual changes, as this could break program functionality.


namespace ChocolateySpreader
{
    public partial class Form1
    {
        /// <summary>
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary>
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Windows Form Designer generated code

        /// <summary>
        /// Required method for Designer support - do not modify
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(Form1));
            this.ISOPathLabel = new System.Windows.Forms.Label();
            this.FolderPathLabel = new System.Windows.Forms.Label();
            this.FolderPathBox = new System.Windows.Forms.TextBox();
            this.ISOPathBox = new System.Windows.Forms.TextBox();
            this.ISOSelectButton = new System.Windows.Forms.Button();
            this.OutputFolderSelectButton = new System.Windows.Forms.Button();
            this.ExtractISOButton = new System.Windows.Forms.Button();
            this.tabControl1 = new System.Windows.Forms.TabControl();
            this.WelcomePage = new System.Windows.Forms.TabPage();
            this.linkLabel4 = new System.Windows.Forms.LinkLabel();
            this.label9 = new System.Windows.Forms.Label();
            this.label8 = new System.Windows.Forms.Label();
            this.pictureBox1 = new System.Windows.Forms.PictureBox();
            this.label7 = new System.Windows.Forms.Label();
            this.label6 = new System.Windows.Forms.Label();
            this.WelcomeLabel = new System.Windows.Forms.Label();
            this.ExtractISOPage = new System.Windows.Forms.TabPage();
            this.OutputFolderHelpButton = new System.Windows.Forms.Button();
            this.ISOPathHelpButton = new System.Windows.Forms.Button();
            this.label20 = new System.Windows.Forms.Label();
            this.SevenZipLinkLabel = new System.Windows.Forms.LinkLabel();
            this.label12 = new System.Windows.Forms.Label();
            this.pictureBox2 = new System.Windows.Forms.PictureBox();
            this.ISOExtractExplainLabel = new System.Windows.Forms.Label();
            this.label4 = new System.Windows.Forms.Label();
            this.OutputExtractBox = new System.Windows.Forms.RichTextBox();
            this.CreateISOPage = new System.Windows.Forms.TabPage();
            this.FinalISOHelpButton = new System.Windows.Forms.Button();
            this.PKGListHelpButton = new System.Windows.Forms.Button();
            this.ISOFolderHelpButton = new System.Windows.Forms.Button();
            this.WinADKLinkLabel = new System.Windows.Forms.LinkLabel();
            this.label21 = new System.Windows.Forms.Label();
            this.label18 = new System.Windows.Forms.Label();
            this.label5 = new System.Windows.Forms.Label();
            this.FinalISOButton = new System.Windows.Forms.Button();
            this.FinalISOPath = new System.Windows.Forms.TextBox();
            this.label3 = new System.Windows.Forms.Label();
            this.label2 = new System.Windows.Forms.Label();
            this.PKGListVersionBox = new System.Windows.Forms.RichTextBox();
            this.label1 = new System.Windows.Forms.Label();
            this.PKGListViewBox = new System.Windows.Forms.RichTextBox();
            this.ChocoExportButton = new System.Windows.Forms.Button();
            this.ChocoSpreadButton = new System.Windows.Forms.Button();
            this.PKGListButton = new System.Windows.Forms.Button();
            this.ISOFolderButton = new System.Windows.Forms.Button();
            this.ISOFolderBox = new System.Windows.Forms.TextBox();
            this.PKGListBox = new System.Windows.Forms.TextBox();
            this.PKGListLabel = new System.Windows.Forms.Label();
            this.ISOFolderLabel = new System.Windows.Forms.Label();
            this.OutputLabel = new System.Windows.Forms.Label();
            this.OutputCreateBox = new System.Windows.Forms.RichTextBox();
            this.ChocoDetectLabel = new System.Windows.Forms.Label();
            this.tabControl1.SuspendLayout();
            this.WelcomePage.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)(this.pictureBox1)).BeginInit();
            this.ExtractISOPage.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)(this.pictureBox2)).BeginInit();
            this.CreateISOPage.SuspendLayout();
            this.SuspendLayout();
            // 
            // ISOPathLabel
            // 
            this.ISOPathLabel.AutoSize = true;
            this.ISOPathLabel.Font = new System.Drawing.Font("Segoe UI", 8.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.ISOPathLabel.ForeColor = System.Drawing.SystemColors.ControlLight;
            this.ISOPathLabel.Location = new System.Drawing.Point(8, 75);
            this.ISOPathLabel.Name = "ISOPathLabel";
            this.ISOPathLabel.Size = new System.Drawing.Size(54, 13);
            this.ISOPathLabel.TabIndex = 0;
            this.ISOPathLabel.Text = "ISO Path:";
            // 
            // FolderPathLabel
            // 
            this.FolderPathLabel.AutoSize = true;
            this.FolderPathLabel.Font = new System.Drawing.Font("Segoe UI", 8.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.FolderPathLabel.ForeColor = System.Drawing.SystemColors.ControlLight;
            this.FolderPathLabel.Location = new System.Drawing.Point(9, 117);
            this.FolderPathLabel.Name = "FolderPathLabel";
            this.FolderPathLabel.Size = new System.Drawing.Size(84, 13);
            this.FolderPathLabel.TabIndex = 1;
            this.FolderPathLabel.Text = "Output Folder:";
            // 
            // FolderPathBox
            // 
            this.FolderPathBox.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(64)))), ((int)(((byte)(64)))), ((int)(((byte)(64)))));
            this.FolderPathBox.BorderStyle = System.Windows.Forms.BorderStyle.FixedSingle;
            this.FolderPathBox.Font = new System.Drawing.Font("Segoe UI", 8.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.FolderPathBox.ForeColor = System.Drawing.SystemColors.Window;
            this.FolderPathBox.Location = new System.Drawing.Point(10, 133);
            this.FolderPathBox.Name = "FolderPathBox";
            this.FolderPathBox.ReadOnly = true;
            this.FolderPathBox.Size = new System.Drawing.Size(361, 22);
            this.FolderPathBox.TabIndex = 2;
            // 
            // ISOPathBox
            // 
            this.ISOPathBox.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(64)))), ((int)(((byte)(64)))), ((int)(((byte)(64)))));
            this.ISOPathBox.BorderStyle = System.Windows.Forms.BorderStyle.FixedSingle;
            this.ISOPathBox.Font = new System.Drawing.Font("Segoe UI", 8.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.ISOPathBox.ForeColor = System.Drawing.SystemColors.Window;
            this.ISOPathBox.Location = new System.Drawing.Point(10, 91);
            this.ISOPathBox.Name = "ISOPathBox";
            this.ISOPathBox.ReadOnly = true;
            this.ISOPathBox.Size = new System.Drawing.Size(361, 22);
            this.ISOPathBox.TabIndex = 3;
            // 
            // ISOSelectButton
            // 
            this.ISOSelectButton.BackColor = System.Drawing.Color.White;
            this.ISOSelectButton.CausesValidation = false;
            this.ISOSelectButton.FlatStyle = System.Windows.Forms.FlatStyle.Popup;
            this.ISOSelectButton.Font = new System.Drawing.Font("Segoe UI", 8.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.ISOSelectButton.Location = new System.Drawing.Point(377, 90);
            this.ISOSelectButton.Name = "ISOSelectButton";
            this.ISOSelectButton.Size = new System.Drawing.Size(75, 22);
            this.ISOSelectButton.TabIndex = 4;
            this.ISOSelectButton.Text = "Browse...";
            this.ISOSelectButton.UseVisualStyleBackColor = false;
            this.ISOSelectButton.Click += new System.EventHandler(this.ISOSelectButton_Click);
            // 
            // OutputFolderSelectButton
            // 
            this.OutputFolderSelectButton.BackColor = System.Drawing.Color.White;
            this.OutputFolderSelectButton.FlatStyle = System.Windows.Forms.FlatStyle.Popup;
            this.OutputFolderSelectButton.Font = new System.Drawing.Font("Segoe UI", 8.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.OutputFolderSelectButton.Location = new System.Drawing.Point(377, 133);
            this.OutputFolderSelectButton.Name = "OutputFolderSelectButton";
            this.OutputFolderSelectButton.Size = new System.Drawing.Size(75, 22);
            this.OutputFolderSelectButton.TabIndex = 5;
            this.OutputFolderSelectButton.Text = "Browse...";
            this.OutputFolderSelectButton.UseVisualStyleBackColor = false;
            this.OutputFolderSelectButton.Click += new System.EventHandler(this.FolderSelectButton_Click);
            // 
            // ExtractISOButton
            // 
            this.ExtractISOButton.BackColor = System.Drawing.Color.White;
            this.ExtractISOButton.FlatStyle = System.Windows.Forms.FlatStyle.Popup;
            this.ExtractISOButton.Font = new System.Drawing.Font("Segoe UI", 8.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.ExtractISOButton.Location = new System.Drawing.Point(159, 161);
            this.ExtractISOButton.Name = "ExtractISOButton";
            this.ExtractISOButton.Size = new System.Drawing.Size(178, 23);
            this.ExtractISOButton.TabIndex = 6;
            this.ExtractISOButton.Text = "Extract ISO";
            this.ExtractISOButton.UseVisualStyleBackColor = false;
            this.ExtractISOButton.Click += new System.EventHandler(this.ExtractISOButton_Click);
            // 
            // tabControl1
            // 
            this.tabControl1.Controls.Add(this.WelcomePage);
            this.tabControl1.Controls.Add(this.ExtractISOPage);
            this.tabControl1.Controls.Add(this.CreateISOPage);
            this.tabControl1.Location = new System.Drawing.Point(0, 2);
            this.tabControl1.Name = "tabControl1";
            this.tabControl1.SelectedIndex = 0;
            this.tabControl1.Size = new System.Drawing.Size(820, 467);
            this.tabControl1.TabIndex = 26;
            // 
            // WelcomePage
            // 
            this.WelcomePage.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(64)))), ((int)(((byte)(64)))), ((int)(((byte)(64)))));
            this.WelcomePage.Controls.Add(this.linkLabel4);
            this.WelcomePage.Controls.Add(this.label9);
            this.WelcomePage.Controls.Add(this.label8);
            this.WelcomePage.Controls.Add(this.pictureBox1);
            this.WelcomePage.Controls.Add(this.label7);
            this.WelcomePage.Controls.Add(this.label6);
            this.WelcomePage.Controls.Add(this.WelcomeLabel);
            this.WelcomePage.Location = new System.Drawing.Point(4, 22);
            this.WelcomePage.Margin = new System.Windows.Forms.Padding(0);
            this.WelcomePage.Name = "WelcomePage";
            this.WelcomePage.Size = new System.Drawing.Size(812, 441);
            this.WelcomePage.TabIndex = 0;
            this.WelcomePage.Text = "Welcome!";
            // 
            // linkLabel4
            // 
            this.linkLabel4.AutoSize = true;
            this.linkLabel4.Font = new System.Drawing.Font("Segoe UI", 8.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.linkLabel4.LinkColor = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(150)))), ((int)(((byte)(255)))));
            this.linkLabel4.Location = new System.Drawing.Point(396, 90);
            this.linkLabel4.Name = "linkLabel4";
            this.linkLabel4.Size = new System.Drawing.Size(33, 13);
            this.linkLabel4.TabIndex = 37;
            this.linkLabel4.TabStop = true;
            this.linkLabel4.Text = "here:";
            this.linkLabel4.LinkClicked += new System.Windows.Forms.LinkLabelLinkClickedEventHandler(this.linkLabel4_LinkClicked);
            // 
            // label9
            // 
            this.label9.AutoSize = true;
            this.label9.Font = new System.Drawing.Font("Segoe UI", 8.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.label9.ForeColor = System.Drawing.SystemColors.ControlLight;
            this.label9.Location = new System.Drawing.Point(0, 90);
            this.label9.Name = "label9";
            this.label9.Size = new System.Drawing.Size(399, 13);
            this.label9.TabIndex = 36;
            this.label9.Text = "This software should always be obtained from its GitHub repository, located";
            // 
            // label8
            // 
            this.label8.AutoSize = true;
            this.label8.Font = new System.Drawing.Font("Segoe UI", 8.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.label8.ForeColor = System.Drawing.SystemColors.ControlLight;
            this.label8.Location = new System.Drawing.Point(0, 69);
            this.label8.Name = "label8";
            this.label8.Size = new System.Drawing.Size(748, 13);
            this.label8.TabIndex = 35;
            this.label8.Text = "ChocolateySpreader and all associated software necessary for full functionality i" +
    "s provided free of charge. This stance is not expected to change.\r\n";
            // 
            // pictureBox1
            // 
            this.pictureBox1.Image = ((System.Drawing.Image)(resources.GetObject("pictureBox1.Image")));
            this.pictureBox1.Location = new System.Drawing.Point(619, 280);
            this.pictureBox1.Name = "pictureBox1";
            this.pictureBox1.Size = new System.Drawing.Size(190, 161);
            this.pictureBox1.SizeMode = System.Windows.Forms.PictureBoxSizeMode.Zoom;
            this.pictureBox1.TabIndex = 34;
            this.pictureBox1.TabStop = false;
            // 
            // label7
            // 
            this.label7.AutoSize = true;
            this.label7.Font = new System.Drawing.Font("Segoe UI", 8.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.label7.ForeColor = System.Drawing.SystemColors.ControlLight;
            this.label7.Location = new System.Drawing.Point(0, 50);
            this.label7.Name = "label7";
            this.label7.Size = new System.Drawing.Size(694, 13);
            this.label7.TabIndex = 33;
            this.label7.Text = "To get started, click on one of the tabs above. Note that additional programs are" +
    " required to ensure full functionality of this program.";
            // 
            // label6
            // 
            this.label6.AutoSize = true;
            this.label6.Font = new System.Drawing.Font("Segoe UI", 8.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.label6.ForeColor = System.Drawing.SystemColors.ControlLight;
            this.label6.Location = new System.Drawing.Point(0, 35);
            this.label6.Name = "label6";
            this.label6.Size = new System.Drawing.Size(644, 13);
            this.label6.TabIndex = 32;
            this.label6.Text = "This application will help you to create a Windows ISO that will automatically in" +
    "stall the programs of your choosing for you.";
            // 
            // WelcomeLabel
            // 
            this.WelcomeLabel.AutoSize = true;
            this.WelcomeLabel.Font = new System.Drawing.Font("Segoe UI", 8.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.WelcomeLabel.ForeColor = System.Drawing.SystemColors.ControlLight;
            this.WelcomeLabel.Location = new System.Drawing.Point(0, 12);
            this.WelcomeLabel.Name = "WelcomeLabel";
            this.WelcomeLabel.Size = new System.Drawing.Size(177, 13);
            this.WelcomeLabel.TabIndex = 30;
            this.WelcomeLabel.Text = "Welcome to ChocolateySpreader!";
            // 
            // ExtractISOPage
            // 
            this.ExtractISOPage.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(64)))), ((int)(((byte)(64)))), ((int)(((byte)(64)))));
            this.ExtractISOPage.Controls.Add(this.OutputFolderHelpButton);
            this.ExtractISOPage.Controls.Add(this.ISOPathHelpButton);
            this.ExtractISOPage.Controls.Add(this.label20);
            this.ExtractISOPage.Controls.Add(this.SevenZipLinkLabel);
            this.ExtractISOPage.Controls.Add(this.label12);
            this.ExtractISOPage.Controls.Add(this.pictureBox2);
            this.ExtractISOPage.Controls.Add(this.ISOExtractExplainLabel);
            this.ExtractISOPage.Controls.Add(this.label4);
            this.ExtractISOPage.Controls.Add(this.OutputExtractBox);
            this.ExtractISOPage.Controls.Add(this.ISOPathLabel);
            this.ExtractISOPage.Controls.Add(this.FolderPathLabel);
            this.ExtractISOPage.Controls.Add(this.FolderPathBox);
            this.ExtractISOPage.Controls.Add(this.ISOPathBox);
            this.ExtractISOPage.Controls.Add(this.ISOSelectButton);
            this.ExtractISOPage.Controls.Add(this.OutputFolderSelectButton);
            this.ExtractISOPage.Controls.Add(this.ExtractISOButton);
            this.ExtractISOPage.Location = new System.Drawing.Point(4, 22);
            this.ExtractISOPage.Name = "ExtractISOPage";
            this.ExtractISOPage.Padding = new System.Windows.Forms.Padding(3);
            this.ExtractISOPage.Size = new System.Drawing.Size(812, 441);
            this.ExtractISOPage.TabIndex = 1;
            this.ExtractISOPage.Text = "Extract ISO";
            // 
            // OutputFolderHelpButton
            // 
            this.OutputFolderHelpButton.BackColor = System.Drawing.Color.White;
            this.OutputFolderHelpButton.FlatStyle = System.Windows.Forms.FlatStyle.Popup;
            this.OutputFolderHelpButton.Font = new System.Drawing.Font("Segoe UI", 8.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.OutputFolderHelpButton.Location = new System.Drawing.Point(458, 133);
            this.OutputFolderHelpButton.Name = "OutputFolderHelpButton";
            this.OutputFolderHelpButton.Size = new System.Drawing.Size(22, 22);
            this.OutputFolderHelpButton.TabIndex = 56;
            this.OutputFolderHelpButton.Text = "?";
            this.OutputFolderHelpButton.UseVisualStyleBackColor = false;
            this.OutputFolderHelpButton.Click += new System.EventHandler(this.OutputFolderHelpButton_Click);
            // 
            // ISOPathHelpButton
            // 
            this.ISOPathHelpButton.BackColor = System.Drawing.Color.White;
            this.ISOPathHelpButton.FlatStyle = System.Windows.Forms.FlatStyle.Popup;
            this.ISOPathHelpButton.Font = new System.Drawing.Font("Segoe UI", 8.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.ISOPathHelpButton.Location = new System.Drawing.Point(458, 90);
            this.ISOPathHelpButton.Name = "ISOPathHelpButton";
            this.ISOPathHelpButton.Size = new System.Drawing.Size(22, 22);
            this.ISOPathHelpButton.TabIndex = 55;
            this.ISOPathHelpButton.Text = "?";
            this.ISOPathHelpButton.UseVisualStyleBackColor = false;
            this.ISOPathHelpButton.Click += new System.EventHandler(this.ISOPathHelpButton_Click);
            // 
            // label20
            // 
            this.label20.AutoSize = true;
            this.label20.Font = new System.Drawing.Font("Segoe UI", 8.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.label20.ForeColor = System.Drawing.SystemColors.ControlLight;
            this.label20.Location = new System.Drawing.Point(6, 20);
            this.label20.MaximumSize = new System.Drawing.Size(800, 0);
            this.label20.Name = "label20";
            this.label20.Size = new System.Drawing.Size(783, 26);
            this.label20.TabIndex = 39;
            this.label20.Text = "Depending on the speed of your computer and your storage devices, the extraction " +
    "process may take a while to complete.  You can track the extraction process via " +
    "the output window below.";
            // 
            // SevenZipLinkLabel
            // 
            this.SevenZipLinkLabel.AutoSize = true;
            this.SevenZipLinkLabel.Font = new System.Drawing.Font("Segoe UI", 8.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.SevenZipLinkLabel.LinkColor = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(150)))), ((int)(((byte)(255)))));
            this.SevenZipLinkLabel.Location = new System.Drawing.Point(217, 52);
            this.SevenZipLinkLabel.Name = "SevenZipLinkLabel";
            this.SevenZipLinkLabel.Size = new System.Drawing.Size(125, 13);
            this.SevenZipLinkLabel.TabIndex = 38;
            this.SevenZipLinkLabel.TabStop = true;
            this.SevenZipLinkLabel.Text = "https://www.7-zip.org/";
            this.SevenZipLinkLabel.LinkClicked += new System.Windows.Forms.LinkLabelLinkClickedEventHandler(this.SevenZipLinkLabel_LinkClicked);
            // 
            // label12
            // 
            this.label12.AutoSize = true;
            this.label12.Font = new System.Drawing.Font("Segoe UI", 8.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.label12.ForeColor = System.Drawing.SystemColors.ControlLight;
            this.label12.Location = new System.Drawing.Point(6, 52);
            this.label12.Name = "label12";
            this.label12.Size = new System.Drawing.Size(211, 13);
            this.label12.TabIndex = 37;
            this.label12.Text = "If 7-Zip is not installed, get it from here:";
            // 
            // pictureBox2
            // 
            this.pictureBox2.Image = ((System.Drawing.Image)(resources.GetObject("pictureBox2.Image")));
            this.pictureBox2.Location = new System.Drawing.Point(619, 280);
            this.pictureBox2.Name = "pictureBox2";
            this.pictureBox2.Size = new System.Drawing.Size(190, 161);
            this.pictureBox2.SizeMode = System.Windows.Forms.PictureBoxSizeMode.Zoom;
            this.pictureBox2.TabIndex = 35;
            this.pictureBox2.TabStop = false;
            // 
            // ISOExtractExplainLabel
            // 
            this.ISOExtractExplainLabel.AutoSize = true;
            this.ISOExtractExplainLabel.Font = new System.Drawing.Font("Segoe UI", 8.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.ISOExtractExplainLabel.ForeColor = System.Drawing.SystemColors.ControlLight;
            this.ISOExtractExplainLabel.Location = new System.Drawing.Point(6, 3);
            this.ISOExtractExplainLabel.MaximumSize = new System.Drawing.Size(1110, 0);
            this.ISOExtractExplainLabel.Name = "ISOExtractExplainLabel";
            this.ISOExtractExplainLabel.Size = new System.Drawing.Size(604, 13);
            this.ISOExtractExplainLabel.TabIndex = 29;
            this.ISOExtractExplainLabel.Text = "Select an ISO and the place to extract the files to using the buttons. 7-Zip is r" +
    "equired to extract the files from an ISO.";
            // 
            // label4
            // 
            this.label4.AutoSize = true;
            this.label4.Font = new System.Drawing.Font("Segoe UI", 8.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.label4.ForeColor = System.Drawing.SystemColors.ControlLight;
            this.label4.Location = new System.Drawing.Point(0, 261);
            this.label4.Name = "label4";
            this.label4.Size = new System.Drawing.Size(45, 13);
            this.label4.TabIndex = 28;
            this.label4.Text = "Output";
            // 
            // OutputExtractBox
            // 
            this.OutputExtractBox.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(64)))), ((int)(((byte)(64)))), ((int)(((byte)(64)))));
            this.OutputExtractBox.BorderStyle = System.Windows.Forms.BorderStyle.FixedSingle;
            this.OutputExtractBox.Font = new System.Drawing.Font("Segoe UI", 8.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.OutputExtractBox.ForeColor = System.Drawing.SystemColors.Window;
            this.OutputExtractBox.Location = new System.Drawing.Point(4, 278);
            this.OutputExtractBox.Name = "OutputExtractBox";
            this.OutputExtractBox.ReadOnly = true;
            this.OutputExtractBox.Size = new System.Drawing.Size(608, 164);
            this.OutputExtractBox.TabIndex = 27;
            this.OutputExtractBox.Text = "";
            // 
            // CreateISOPage
            // 
            this.CreateISOPage.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(64)))), ((int)(((byte)(64)))), ((int)(((byte)(64)))));
            this.CreateISOPage.Controls.Add(this.FinalISOHelpButton);
            this.CreateISOPage.Controls.Add(this.PKGListHelpButton);
            this.CreateISOPage.Controls.Add(this.ISOFolderHelpButton);
            this.CreateISOPage.Controls.Add(this.WinADKLinkLabel);
            this.CreateISOPage.Controls.Add(this.label21);
            this.CreateISOPage.Controls.Add(this.label18);
            this.CreateISOPage.Controls.Add(this.label5);
            this.CreateISOPage.Controls.Add(this.FinalISOButton);
            this.CreateISOPage.Controls.Add(this.FinalISOPath);
            this.CreateISOPage.Controls.Add(this.label3);
            this.CreateISOPage.Controls.Add(this.label2);
            this.CreateISOPage.Controls.Add(this.PKGListVersionBox);
            this.CreateISOPage.Controls.Add(this.label1);
            this.CreateISOPage.Controls.Add(this.PKGListViewBox);
            this.CreateISOPage.Controls.Add(this.ChocoExportButton);
            this.CreateISOPage.Controls.Add(this.ChocoSpreadButton);
            this.CreateISOPage.Controls.Add(this.PKGListButton);
            this.CreateISOPage.Controls.Add(this.ISOFolderButton);
            this.CreateISOPage.Controls.Add(this.ISOFolderBox);
            this.CreateISOPage.Controls.Add(this.PKGListBox);
            this.CreateISOPage.Controls.Add(this.PKGListLabel);
            this.CreateISOPage.Controls.Add(this.ISOFolderLabel);
            this.CreateISOPage.Controls.Add(this.OutputLabel);
            this.CreateISOPage.Controls.Add(this.OutputCreateBox);
            this.CreateISOPage.Controls.Add(this.ChocoDetectLabel);
            this.CreateISOPage.ForeColor = System.Drawing.SystemColors.ControlText;
            this.CreateISOPage.Location = new System.Drawing.Point(4, 22);
            this.CreateISOPage.Name = "CreateISOPage";
            this.CreateISOPage.Padding = new System.Windows.Forms.Padding(3);
            this.CreateISOPage.Size = new System.Drawing.Size(812, 441);
            this.CreateISOPage.TabIndex = 2;
            this.CreateISOPage.Text = "Create New ISO";
            // 
            // FinalISOHelpButton
            // 
            this.FinalISOHelpButton.BackColor = System.Drawing.Color.White;
            this.FinalISOHelpButton.FlatStyle = System.Windows.Forms.FlatStyle.Popup;
            this.FinalISOHelpButton.Font = new System.Drawing.Font("Segoe UI", 8.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.FinalISOHelpButton.Location = new System.Drawing.Point(264, 107);
            this.FinalISOHelpButton.Name = "FinalISOHelpButton";
            this.FinalISOHelpButton.Size = new System.Drawing.Size(24, 24);
            this.FinalISOHelpButton.TabIndex = 56;
            this.FinalISOHelpButton.Text = "?";
            this.FinalISOHelpButton.UseVisualStyleBackColor = false;
            this.FinalISOHelpButton.Click += new System.EventHandler(this.FinalISOHelpButton_Click);
            // 
            // PKGListHelpButton
            // 
            this.PKGListHelpButton.BackColor = System.Drawing.Color.White;
            this.PKGListHelpButton.FlatStyle = System.Windows.Forms.FlatStyle.Popup;
            this.PKGListHelpButton.Font = new System.Drawing.Font("Segoe UI", 8.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.PKGListHelpButton.Location = new System.Drawing.Point(264, 68);
            this.PKGListHelpButton.Name = "PKGListHelpButton";
            this.PKGListHelpButton.Size = new System.Drawing.Size(24, 24);
            this.PKGListHelpButton.TabIndex = 55;
            this.PKGListHelpButton.Text = "?";
            this.PKGListHelpButton.UseVisualStyleBackColor = false;
            this.PKGListHelpButton.Click += new System.EventHandler(this.PKGListHelpButton_Click);
            // 
            // ISOFolderHelpButton
            // 
            this.ISOFolderHelpButton.BackColor = System.Drawing.Color.White;
            this.ISOFolderHelpButton.FlatStyle = System.Windows.Forms.FlatStyle.Popup;
            this.ISOFolderHelpButton.Font = new System.Drawing.Font("Segoe UI", 8.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.ISOFolderHelpButton.Location = new System.Drawing.Point(264, 31);
            this.ISOFolderHelpButton.Name = "ISOFolderHelpButton";
            this.ISOFolderHelpButton.Size = new System.Drawing.Size(24, 24);
            this.ISOFolderHelpButton.TabIndex = 54;
            this.ISOFolderHelpButton.Text = "?";
            this.ISOFolderHelpButton.UseVisualStyleBackColor = false;
            this.ISOFolderHelpButton.Click += new System.EventHandler(this.ISOFolderHelpButton_Click);
            // 
            // WinADKLinkLabel
            // 
            this.WinADKLinkLabel.AutoSize = true;
            this.WinADKLinkLabel.Font = new System.Drawing.Font("Segoe UI", 8.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.WinADKLinkLabel.LinkColor = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(150)))), ((int)(((byte)(255)))));
            this.WinADKLinkLabel.Location = new System.Drawing.Point(600, 95);
            this.WinADKLinkLabel.Name = "WinADKLinkLabel";
            this.WinADKLinkLabel.Size = new System.Drawing.Size(33, 13);
            this.WinADKLinkLabel.TabIndex = 53;
            this.WinADKLinkLabel.TabStop = true;
            this.WinADKLinkLabel.Text = "here:";
            this.WinADKLinkLabel.LinkClicked += new System.Windows.Forms.LinkLabelLinkClickedEventHandler(this.WinADKLinkLabel_LinkClicked);
            // 
            // label21
            // 
            this.label21.AutoSize = true;
            this.label21.Font = new System.Drawing.Font("Segoe UI", 8.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.label21.ForeColor = System.Drawing.SystemColors.ControlLight;
            this.label21.Location = new System.Drawing.Point(320, 82);
            this.label21.MaximumSize = new System.Drawing.Size(490, 0);
            this.label21.Name = "label21";
            this.label21.Size = new System.Drawing.Size(439, 26);
            this.label21.TabIndex = 52;
            this.label21.Text = "Creating a new bootable ISO requires the Deployment Tools found in the Windows As" +
    "sessment and Deployment kit. This can be obtained";
            // 
            // label18
            // 
            this.label18.AutoSize = true;
            this.label18.Font = new System.Drawing.Font("Segoe UI", 8.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.label18.ForeColor = System.Drawing.SystemColors.ControlLight;
            this.label18.Location = new System.Drawing.Point(321, 37);
            this.label18.MaximumSize = new System.Drawing.Size(490, 0);
            this.label18.Name = "label18";
            this.label18.Size = new System.Drawing.Size(481, 39);
            this.label18.TabIndex = 49;
            this.label18.Text = resources.GetString("label18.Text");
            // 
            // label5
            // 
            this.label5.Font = new System.Drawing.Font("Segoe UI", 8.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.label5.ForeColor = System.Drawing.SystemColors.ControlLight;
            this.label5.Location = new System.Drawing.Point(322, 5);
            this.label5.MaximumSize = new System.Drawing.Size(500, 500);
            this.label5.Name = "label5";
            this.label5.Size = new System.Drawing.Size(494, 29);
            this.label5.TabIndex = 43;
            this.label5.Text = "Use this page to create a Windows ISO that will automatically install Chocolatey " +
    "and the packages of your choosing for you.";
            // 
            // FinalISOButton
            // 
            this.FinalISOButton.BackColor = System.Drawing.Color.White;
            this.FinalISOButton.FlatStyle = System.Windows.Forms.FlatStyle.Popup;
            this.FinalISOButton.Font = new System.Drawing.Font("Segoe UI", 8.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.FinalISOButton.ForeColor = System.Drawing.SystemColors.ControlText;
            this.FinalISOButton.Location = new System.Drawing.Point(184, 107);
            this.FinalISOButton.Name = "FinalISOButton";
            this.FinalISOButton.Size = new System.Drawing.Size(75, 24);
            this.FinalISOButton.TabIndex = 42;
            this.FinalISOButton.Text = "Browse...";
            this.FinalISOButton.UseVisualStyleBackColor = false;
            this.FinalISOButton.Click += new System.EventHandler(this.FinalISOButton_Click);
            // 
            // FinalISOPath
            // 
            this.FinalISOPath.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(64)))), ((int)(((byte)(64)))), ((int)(((byte)(64)))));
            this.FinalISOPath.BorderStyle = System.Windows.Forms.BorderStyle.FixedSingle;
            this.FinalISOPath.Font = new System.Drawing.Font("Segoe UI", 8.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.FinalISOPath.ForeColor = System.Drawing.SystemColors.Window;
            this.FinalISOPath.Location = new System.Drawing.Point(7, 107);
            this.FinalISOPath.Name = "FinalISOPath";
            this.FinalISOPath.ReadOnly = true;
            this.FinalISOPath.Size = new System.Drawing.Size(167, 22);
            this.FinalISOPath.TabIndex = 41;
            // 
            // label3
            // 
            this.label3.AutoSize = true;
            this.label3.Font = new System.Drawing.Font("Segoe UI", 8.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.label3.ForeColor = System.Drawing.SystemColors.ControlLight;
            this.label3.Location = new System.Drawing.Point(5, 91);
            this.label3.Name = "label3";
            this.label3.Size = new System.Drawing.Size(69, 13);
            this.label3.TabIndex = 40;
            this.label3.Text = "Output ISO:";
            // 
            // label2
            // 
            this.label2.AutoSize = true;
            this.label2.Font = new System.Drawing.Font("Segoe UI", 8.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.label2.ForeColor = System.Drawing.SystemColors.ControlLight;
            this.label2.Location = new System.Drawing.Point(629, 271);
            this.label2.Name = "label2";
            this.label2.Size = new System.Drawing.Size(48, 13);
            this.label2.TabIndex = 39;
            this.label2.Text = "Version:";
            // 
            // PKGListVersionBox
            // 
            this.PKGListVersionBox.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(64)))), ((int)(((byte)(64)))), ((int)(((byte)(64)))));
            this.PKGListVersionBox.BorderStyle = System.Windows.Forms.BorderStyle.FixedSingle;
            this.PKGListVersionBox.Font = new System.Drawing.Font("Segoe UI", 8.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.PKGListVersionBox.ForeColor = System.Drawing.SystemColors.Window;
            this.PKGListVersionBox.Location = new System.Drawing.Point(632, 287);
            this.PKGListVersionBox.Name = "PKGListVersionBox";
            this.PKGListVersionBox.ReadOnly = true;
            this.PKGListVersionBox.Size = new System.Drawing.Size(179, 159);
            this.PKGListVersionBox.TabIndex = 38;
            this.PKGListVersionBox.Text = "No package list loaded.";
            this.PKGListVersionBox.VScroll += new System.EventHandler(this.PKGListVersionBox_VScroll);
            // 
            // label1
            // 
            this.label1.AutoSize = true;
            this.label1.Font = new System.Drawing.Font("Segoe UI", 8.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.label1.ForeColor = System.Drawing.SystemColors.ControlLight;
            this.label1.Location = new System.Drawing.Point(413, 268);
            this.label1.Name = "label1";
            this.label1.Size = new System.Drawing.Size(57, 13);
            this.label1.TabIndex = 37;
            this.label1.Text = "Packages:";
            // 
            // PKGListViewBox
            // 
            this.PKGListViewBox.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(64)))), ((int)(((byte)(64)))), ((int)(((byte)(64)))));
            this.PKGListViewBox.BorderStyle = System.Windows.Forms.BorderStyle.FixedSingle;
            this.PKGListViewBox.Font = new System.Drawing.Font("Segoe UI", 8.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.PKGListViewBox.ForeColor = System.Drawing.SystemColors.Window;
            this.PKGListViewBox.Location = new System.Drawing.Point(416, 287);
            this.PKGListViewBox.Name = "PKGListViewBox";
            this.PKGListViewBox.ReadOnly = true;
            this.PKGListViewBox.ScrollBars = System.Windows.Forms.RichTextBoxScrollBars.None;
            this.PKGListViewBox.Size = new System.Drawing.Size(219, 156);
            this.PKGListViewBox.TabIndex = 36;
            this.PKGListViewBox.Text = "No package list loaded.";
            this.PKGListViewBox.VScroll += new System.EventHandler(this.PKGListViewBox_VScroll);
            // 
            // ChocoExportButton
            // 
            this.ChocoExportButton.BackColor = System.Drawing.Color.White;
            this.ChocoExportButton.FlatStyle = System.Windows.Forms.FlatStyle.Popup;
            this.ChocoExportButton.Font = new System.Drawing.Font("Segoe UI", 8.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.ChocoExportButton.ForeColor = System.Drawing.SystemColors.ControlText;
            this.ChocoExportButton.Location = new System.Drawing.Point(11, 229);
            this.ChocoExportButton.Name = "ChocoExportButton";
            this.ChocoExportButton.Size = new System.Drawing.Size(147, 23);
            this.ChocoExportButton.TabIndex = 35;
            this.ChocoExportButton.Text = "Export Package List";
            this.ChocoExportButton.UseVisualStyleBackColor = false;
            this.ChocoExportButton.Click += new System.EventHandler(this.ChocoExportButton_Click);
            // 
            // ChocoSpreadButton
            // 
            this.ChocoSpreadButton.BackColor = System.Drawing.Color.White;
            this.ChocoSpreadButton.FlatStyle = System.Windows.Forms.FlatStyle.Popup;
            this.ChocoSpreadButton.Font = new System.Drawing.Font("Segoe UI", 8.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.ChocoSpreadButton.ForeColor = System.Drawing.SystemColors.ControlText;
            this.ChocoSpreadButton.Location = new System.Drawing.Point(7, 150);
            this.ChocoSpreadButton.Name = "ChocoSpreadButton";
            this.ChocoSpreadButton.Size = new System.Drawing.Size(252, 23);
            this.ChocoSpreadButton.TabIndex = 34;
            this.ChocoSpreadButton.Text = "Insert Scripts and Create ISO";
            this.ChocoSpreadButton.UseVisualStyleBackColor = false;
            this.ChocoSpreadButton.Click += new System.EventHandler(this.ChocoSpreadButton_Click);
            // 
            // PKGListButton
            // 
            this.PKGListButton.BackColor = System.Drawing.Color.White;
            this.PKGListButton.FlatStyle = System.Windows.Forms.FlatStyle.Popup;
            this.PKGListButton.Font = new System.Drawing.Font("Segoe UI", 8.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.PKGListButton.ForeColor = System.Drawing.SystemColors.ControlText;
            this.PKGListButton.Location = new System.Drawing.Point(184, 68);
            this.PKGListButton.Name = "PKGListButton";
            this.PKGListButton.Size = new System.Drawing.Size(75, 24);
            this.PKGListButton.TabIndex = 33;
            this.PKGListButton.Text = "Browse...";
            this.PKGListButton.UseVisualStyleBackColor = false;
            this.PKGListButton.Click += new System.EventHandler(this.PKGListButton_Click);
            // 
            // ISOFolderButton
            // 
            this.ISOFolderButton.BackColor = System.Drawing.Color.White;
            this.ISOFolderButton.FlatStyle = System.Windows.Forms.FlatStyle.Popup;
            this.ISOFolderButton.Font = new System.Drawing.Font("Segoe UI", 8.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.ISOFolderButton.ForeColor = System.Drawing.SystemColors.ControlText;
            this.ISOFolderButton.Location = new System.Drawing.Point(184, 31);
            this.ISOFolderButton.Name = "ISOFolderButton";
            this.ISOFolderButton.Size = new System.Drawing.Size(75, 24);
            this.ISOFolderButton.TabIndex = 32;
            this.ISOFolderButton.Text = "Browse...";
            this.ISOFolderButton.UseVisualStyleBackColor = false;
            this.ISOFolderButton.Click += new System.EventHandler(this.ISOFolderButton_Click);
            // 
            // ISOFolderBox
            // 
            this.ISOFolderBox.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(64)))), ((int)(((byte)(64)))), ((int)(((byte)(64)))));
            this.ISOFolderBox.BorderStyle = System.Windows.Forms.BorderStyle.FixedSingle;
            this.ISOFolderBox.Font = new System.Drawing.Font("Segoe UI", 8.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.ISOFolderBox.ForeColor = System.Drawing.SystemColors.Window;
            this.ISOFolderBox.Location = new System.Drawing.Point(6, 32);
            this.ISOFolderBox.Name = "ISOFolderBox";
            this.ISOFolderBox.ReadOnly = true;
            this.ISOFolderBox.Size = new System.Drawing.Size(168, 22);
            this.ISOFolderBox.TabIndex = 31;
            // 
            // PKGListBox
            // 
            this.PKGListBox.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(64)))), ((int)(((byte)(64)))), ((int)(((byte)(64)))));
            this.PKGListBox.BorderStyle = System.Windows.Forms.BorderStyle.FixedSingle;
            this.PKGListBox.Font = new System.Drawing.Font("Segoe UI", 8.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.PKGListBox.ForeColor = System.Drawing.SystemColors.Window;
            this.PKGListBox.Location = new System.Drawing.Point(7, 69);
            this.PKGListBox.Name = "PKGListBox";
            this.PKGListBox.ReadOnly = true;
            this.PKGListBox.Size = new System.Drawing.Size(167, 22);
            this.PKGListBox.TabIndex = 30;
            // 
            // PKGListLabel
            // 
            this.PKGListLabel.AutoSize = true;
            this.PKGListLabel.Font = new System.Drawing.Font("Segoe UI", 8.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.PKGListLabel.ForeColor = System.Drawing.SystemColors.ControlLight;
            this.PKGListLabel.Location = new System.Drawing.Point(5, 53);
            this.PKGListLabel.Name = "PKGListLabel";
            this.PKGListLabel.Size = new System.Drawing.Size(72, 13);
            this.PKGListLabel.TabIndex = 29;
            this.PKGListLabel.Text = "Package List:";
            // 
            // ISOFolderLabel
            // 
            this.ISOFolderLabel.AutoSize = true;
            this.ISOFolderLabel.Font = new System.Drawing.Font("Segoe UI", 8.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.ISOFolderLabel.ForeColor = System.Drawing.SystemColors.ControlLight;
            this.ISOFolderLabel.Location = new System.Drawing.Point(4, 15);
            this.ISOFolderLabel.Name = "ISOFolderLabel";
            this.ISOFolderLabel.Size = new System.Drawing.Size(64, 13);
            this.ISOFolderLabel.TabIndex = 28;
            this.ISOFolderLabel.Text = "ISO Folder:";
            // 
            // OutputLabel
            // 
            this.OutputLabel.AutoSize = true;
            this.OutputLabel.Font = new System.Drawing.Font("Segoe UI", 8.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.OutputLabel.ForeColor = System.Drawing.SystemColors.ControlLight;
            this.OutputLabel.Location = new System.Drawing.Point(0, 271);
            this.OutputLabel.Name = "OutputLabel";
            this.OutputLabel.Size = new System.Drawing.Size(45, 13);
            this.OutputLabel.TabIndex = 27;
            this.OutputLabel.Text = "Output";
            // 
            // OutputCreateBox
            // 
            this.OutputCreateBox.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(64)))), ((int)(((byte)(64)))), ((int)(((byte)(64)))));
            this.OutputCreateBox.BorderStyle = System.Windows.Forms.BorderStyle.FixedSingle;
            this.OutputCreateBox.Font = new System.Drawing.Font("Segoe UI", 8.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.OutputCreateBox.ForeColor = System.Drawing.SystemColors.Window;
            this.OutputCreateBox.Location = new System.Drawing.Point(4, 287);
            this.OutputCreateBox.Name = "OutputCreateBox";
            this.OutputCreateBox.ReadOnly = true;
            this.OutputCreateBox.Size = new System.Drawing.Size(415, 159);
            this.OutputCreateBox.TabIndex = 26;
            this.OutputCreateBox.Text = "";
            // 
            // ChocoDetectLabel
            // 
            this.ChocoDetectLabel.AutoSize = true;
            this.ChocoDetectLabel.Font = new System.Drawing.Font("Segoe UI", 8.25F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.ChocoDetectLabel.ForeColor = System.Drawing.Color.LimeGreen;
            this.ChocoDetectLabel.Location = new System.Drawing.Point(16, 213);
            this.ChocoDetectLabel.Name = "ChocoDetectLabel";
            this.ChocoDetectLabel.Size = new System.Drawing.Size(137, 13);
            this.ChocoDetectLabel.TabIndex = 17;
            this.ChocoDetectLabel.Text = "Chocolatey Not Detected";
            // 
            // Form1
            // 
            this.AutoScaleDimensions = new System.Drawing.SizeF(6F, 13F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(64)))), ((int)(((byte)(64)))), ((int)(((byte)(64)))));
            this.BackgroundImageLayout = System.Windows.Forms.ImageLayout.None;
            this.ClientSize = new System.Drawing.Size(822, 470);
            this.Controls.Add(this.tabControl1);
            this.ForeColor = System.Drawing.SystemColors.ControlText;
            this.FormBorderStyle = System.Windows.Forms.FormBorderStyle.FixedSingle;
            this.Icon = ((System.Drawing.Icon)(resources.GetObject("$this.Icon")));
            this.MaximizeBox = false;
            this.Name = "Form1";
            this.Text = "ChocolateySpreader";
            this.Load += new System.EventHandler(this.Form1_Load);
            this.tabControl1.ResumeLayout(false);
            this.WelcomePage.ResumeLayout(false);
            this.WelcomePage.PerformLayout();
            ((System.ComponentModel.ISupportInitialize)(this.pictureBox1)).EndInit();
            this.ExtractISOPage.ResumeLayout(false);
            this.ExtractISOPage.PerformLayout();
            ((System.ComponentModel.ISupportInitialize)(this.pictureBox2)).EndInit();
            this.CreateISOPage.ResumeLayout(false);
            this.CreateISOPage.PerformLayout();
            this.ResumeLayout(false);

        }

        #endregion

        public System.Windows.Forms.Label ISOPathLabel;
        public System.Windows.Forms.Label FolderPathLabel;
        public System.Windows.Forms.TextBox FolderPathBox;
        public System.Windows.Forms.TextBox ISOPathBox;
        public System.Windows.Forms.Button ISOSelectButton;
        public System.Windows.Forms.Button OutputFolderSelectButton;
        public System.Windows.Forms.Button ExtractISOButton;
        private System.Windows.Forms.TabControl tabControl1;
        private System.Windows.Forms.TabPage WelcomePage;
        private System.Windows.Forms.TabPage ExtractISOPage;
        private System.Windows.Forms.TabPage CreateISOPage;
        public System.Windows.Forms.Label label4;
        public System.Windows.Forms.RichTextBox OutputExtractBox;
        public System.Windows.Forms.Button FinalISOButton;
        public System.Windows.Forms.TextBox FinalISOPath;
        public System.Windows.Forms.Label label3;
        public System.Windows.Forms.Label label2;
        public System.Windows.Forms.RichTextBox PKGListVersionBox;
        public System.Windows.Forms.Label label1;
        public System.Windows.Forms.RichTextBox PKGListViewBox;
        public System.Windows.Forms.Button ChocoExportButton;
        public System.Windows.Forms.Button ChocoSpreadButton;
        public System.Windows.Forms.Button PKGListButton;
        public System.Windows.Forms.Button ISOFolderButton;
        public System.Windows.Forms.TextBox PKGListBox;
        public System.Windows.Forms.Label PKGListLabel;
        public System.Windows.Forms.Label ISOFolderLabel;
        public System.Windows.Forms.Label OutputLabel;
        public System.Windows.Forms.RichTextBox OutputCreateBox;
        public System.Windows.Forms.Label ChocoDetectLabel;
        private System.Windows.Forms.Label ISOExtractExplainLabel;
        private System.Windows.Forms.Label WelcomeLabel;
        private System.Windows.Forms.Label label6;
        private System.Windows.Forms.Label label7;
        private System.Windows.Forms.PictureBox pictureBox1;
        private System.Windows.Forms.PictureBox pictureBox2;
        private System.Windows.Forms.Label label5;
        private System.Windows.Forms.Label label9;
        private System.Windows.Forms.Label label8;
        private System.Windows.Forms.LinkLabel SevenZipLinkLabel;
        private System.Windows.Forms.Label label12;
        private System.Windows.Forms.Label label18;
        private System.Windows.Forms.Label label20;
        private System.Windows.Forms.LinkLabel WinADKLinkLabel;
        private System.Windows.Forms.Label label21;
        private System.Windows.Forms.LinkLabel linkLabel4;
        public System.Windows.Forms.TextBox ISOFolderBox;
        private System.Windows.Forms.Button FinalISOHelpButton;
        private System.Windows.Forms.Button PKGListHelpButton;
        private System.Windows.Forms.Button ISOFolderHelpButton;
        private System.Windows.Forms.Button OutputFolderHelpButton;
        private System.Windows.Forms.Button ISOPathHelpButton;
    }
}

